name: shelfsdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.4

dependencies:
  crypto: ^3.0.5
  freezed_annotation: ^3.1.0
  dio: ^5.9.0
  http: ^1.2.1
  http_parser: ^4.0.2
  json_annotation: ^4.9.0
  mime: ^2.0.0
  socket_io_client: ^3.0.0-beta.2

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^3.2.4
  json_serializable: ^6.11.3
  lints: ^4.0.0
  mocktail: ^1.0.3
  source_gen: ^4.1.1
  test: ^1.29.0 
